### ISSUE TITLE
TripoSR Viewer don show the 3d model

### ISSUE THREAD

**Issue by kakachiex2** [flowtyone/ComfyUI-Flowty-TripoSR#12]
Wen generates the process complete but at the end nothing shows in the 3d viewer.
![Screenshot 2024-03-06 040925](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/1762112/e437e7d1-0af5-483c-8ad9-86aba15a635b)

**Comment by kakachiex2** [comment]
everything is installed correctly, no errors nothing for know.

**Comment by kakachiex2** [comment]
Wokflow from your example nothing in the viewer
![Screenshot 2024-03-06 041601](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/1762112/49c78aa9-7c10-46ee-969b-7adc54c75625)

**Comment by kakachiex2** [comment]
And can you add option for background color in the viewer and some hdr lighting, so model looks better similar to the implementation in hugging face.

**Comment by cpunion** [comment]
Same with me. The generated model file is saved in `output/` folder, but not show.

**Comment by flowtyone** [comment]
Hi @kakachiex2 looks like you've installed a fork of my nodes, not from this repository. Please raise an issue in Zho's repo: https://github.com/ZHO-ZHO-ZHO/ComfyUI-Flowty-TripoSR-ZHO

**Comment by yelpeach** [comment]
Please check if you have [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack)  installed, the latest ComfyUI-3D-Pack may conflict with this repo.
and if you use [ComfyUI-Flowty-TripoSR-ZHO](https://github.com/ZHO-ZHO-ZHO/ComfyUI-Flowty-TripoSR-ZHO), you should change the name "custom_nodes/ComfyUI-Flowty-TripoSR-ZHO" to "custom_nodes/ComfyUI-Flowty-TripoSR"
