### ISSUE TITLE
Save mesh node

### ISSUE THREAD

**Issue by Foolsets** [flowtyone/ComfyUI-Flowty-TripoSR#13]
I am rly missing save mesh node (

**Comment by ShockWave2048** [comment]
Yes, I agree, how to save the mesh? Is it mesh operator/node from ComfyUI-3D-Pack?

**Comment by flowtyone** [comment]
@ShockWave2048 @Foolsets the meshes are already saved as obj files in your output folder when you're using the triposrviewer node

**Comment by ShockWave2048** [comment]
Thanks!

**Comment by jags111** [comment]
was about to ask same and got the feedback. Later would love other options to save the texture or UV data also so can change or apply to the mesh.

**Comment by flowtyone** [comment]
Closing as the question was answered

**Comment by JamesLaFritz** [comment]
@flowtyone, what about the texture information for the mesh, do I have to manually save out the image with the mask applied?
