### ISSUE TITLE
TripoSR Viewer did not show the model

### ISSUE THREAD

**Issue by BoosterCore** [flowtyone/ComfyUI-Flowty-TripoSR#17]
<img width="1093" alt="屏幕截图 2024-03-06 224225" src="https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/73834045/7a77e78e-7b09-4b27-bb80-1bb37500aeb7">

TripoSR Viewer did not show the model, no error in the CMD window.

<img width="711" alt="屏幕截图 2024-03-06 224540" src="https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/73834045/25f47de5-6f66-4ccd-8a74-00eac01b6225">

**Comment by jmanhype** [comment]
same error

**Comment by flowtyone** [comment]
Can you check for errors in the browser developer tools?

**Comment by yelpeach** [comment]
I have the same problem, and the browser logs looks normal.
![image](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/130973382/8e04bc36-614c-4870-beba-28d30e82b920)

**Comment by flowtyone** [comment]
Can you try to update your comfyui installation?

**Comment by kakachiex2** [comment]
Testing today 3DPack implementation and Flowty TripoSR Workflow flowty dont show the mesh.
![Screenshot 2024-03-07 155349](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/1762112/7090e02c-1c15-4c30-bd75-e2cb1e65a991)

**Comment by kakachiex2** [comment]
I'm using your repo not ZHO, and there is any error of conflict with 3DPack ComfyUI will tell in the screenshot there is two workflow everyone with his own node setup you can see in screenshot. Any error it processes everything correctly is the viewer the problem.

**Comment by solomon-s2020** [comment]
ComfyUI-3D-Pack and ComfyUI-Flowty-TripoSR same registerExtension name "Mr.ForExample.Visualizer.GS".
edit js file:   custom_nodes\ComfyUI-Flowty-TripoSR\web\visualization.js

`app.registerExtension({
    name: "Mr.ForExample.Visualizer.GS",

    async init (app) {

    },

    async beforeRegisterNodeDef(nodeType, nodeData, app) {
        registerVisualizer(nodeType, nodeData, "TripoSRViewer", "threeVisualizer")
    },
})`

to 

`app.registerExtension({
    name: "Mr.ForExample.Visualizer_new.GS",

    async init (app) {

    },

    async beforeRegisterNodeDef(nodeType, nodeData, app) {
        registerVisualizer(nodeType, nodeData, "TripoSRViewer", "threeVisualizer")
    },
})`

save file.
F5
OK

**Comment by solomon-s2020** [comment]
![image](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/89243906/b83169fa-05b2-4359-b9e0-a3ceb22faa48)
