### ISSUE TITLE
saving model and texture

### ISSUE THREAD

**Issue by RYG81** [flowtyone/ComfyUI-Flowty-TripoSR#19]
Hey, good node, really.
But how would you save model with texture? unwrapping texture possible? 
Also when going for 1024 geometry resolution it requires high VRAM, can we have better memory management? Also its good for basic models, little complex model and it just flat or fail creation.
What is threshold? how to use it to improve mesh quality?

**Comment by RYG81** [comment]
![image](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/10570236/1f4eb313-2dac-4f1b-ac41-db1f2990bfaf)
how to overcome this issue

**Comment by ShockWave2048** [comment]
Really need model settings and texture!! PlzPlzPlz!!

**Comment by flowtyone** [comment]
Hi please raise these types of issues in the original TripoSR repository, as I'm not the original developer of the implementation itself - https://github.com/VAST-AI-Research/TripoSR

**Comment by ShockWave2048** [comment]
Ok

**Comment by RYG81** [comment]
On their demo page here - https://huggingface.co/spaces/stabilityai/TripoSR
they have option to save as glb format, so if possible for you please add that feature

**Comment by 3blackbar** [comment]
without saving texture, this node is kinda useless

**Comment by mlo0352** [comment]
None of the .obj files I have locally have any color data. I'm trying to see where in the code things are saved, I imagine it's just not saving the color data, although in the original TripoSR code, I thought it automatically saved.

**Comment by hypervoxel** [comment]
Is there no way to save the texture? In the preview 3d mesh in Comfy, the model is textured. Is this baked into the .obj model?
