### ISSUE TITLE
How is background removal done here?

### ISSUE THREAD

**Issue by CyberTimon** [flowtyone/ComfyUI-Flowty-TripoSR#2]
Thanks for these nodes! I will try them soon. Right now I'm asking myself how the background is removed / or if I have to input the image with already transparent background. 

Kind regards,
Timon

**Comment by flowtyone** [comment]
Hi! You can use comfyui-essentials nodes to remove the background with rembg. In my tests, for some reason results were better with just white background images

**Comment by CyberTimon** [comment]
Amazing! I didn't saw the remove_background function in the code and I planned to use a different model for background removal anyways so this is perfect. Thanks again.
