### ISSUE TITLE
Error loading TripoSR model in ComfyUI

### ISSUE THREAD

**Issue by NetAndif** [flowtyone/ComfyUI-Flowty-TripoSR#20]
Hi, thank you for creating these nodes.
Unfortunately the model doesn't load in my ComfyUI installation:

> Loading TripoSR model
> ERROR:root:!!! Exception during processing !!!
> ERROR:root:Traceback (most recent call last):
>   File "D:\ComfyUI\execution.py", line 152, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\ComfyUI\execution.py", line 82, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\__init__.py", line 45, in load
>     self.initialized_model = TSR.from_pretrained_custom(
>   File "D:\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\system.py", line 80, in from_pretrained_custom
>     ckpt = torch.load(weight_path, map_location="cpu")
>   File "C:\Users\netandif\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1028, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "C:\Users\netandif\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1246, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '<'.

Do you have any idea, why this could happen? I would really love to try it.

**Comment by shynesss** [comment]
same problem

**Comment by LogeshbharathiV** [comment]
I got working flow you can try this in jarvislabs.ai website I used that

**Comment by flowtyone** [comment]
I'm hosting the official implementation in my own cloud website, https://flowt.ai
