### ISSUE TITLE
viewer issue

### ISSUE THREAD

**Issue by ys241015445** [flowtyone/ComfyUI-Flowty-TripoSR#21]
my viewer got some problem after process model..anyone know how to solve it?
![image](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/3347104/a9298155-3f88-4ee1-8584-6205103db92b)

**Comment by yelpeach** [comment]
404 Not Found

**Comment by flowtyone** [comment]
Perhaps you need to update you comfyui version

**Comment by shiccup** [comment]
i am also having a refused to connect error. installed from comfyui manager so there really shouldnt be any naming issues idk what yelpeach is talking about with the 3d pack comment. would still love to find a solution I was able to get this to run on a fresh install comfyui I am guessing theres probably a conflicting node somewhere but not sure which it would be.

**Comment by ys241015445** [comment]
> Also dont change the name file name of your custom node inside custom_nodes folder. It should be named exactly "ComfyUI-Flowty-TripoSR".

yes...I solve the issue in this way.

**Comment by yelpeach** [comment]
> "404 Not Found" maybe you should put [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack) in custom_nodes folder.

my bad, I think the latest [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack) may conflict with this repo.
and if you use [ComfyUI-Flowty-TripoSR-ZHO](https://github.com/ZHO-ZHO-ZHO/ComfyUI-Flowty-TripoSR-ZHO), you shuold change the name "custom_nodes/ComfyUI-Flowty-TripoSR-ZHO" to "custom_nodes/ComfyUI-Flowty-TripoSR"
