### ISSUE TITLE
"reference_mask" input inverted from reference image mask.

### ISSUE THREAD

**Issue by genericgod** [flowtyone/ComfyUI-Flowty-TripoSR#25]
When I want to use an image with alpha and use the "MASK" output for "reference_mask" it only works with the mask inverted.
Is this intentional?

![Bildschirmfoto 2024-03-07 um 18 54 59](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/131956739/8f53a1da-a3b2-41c2-95e5-25c5cf26cb72)
![Bildschirmfoto 2024-03-07 um 18 59 10](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/131956739/f1d4d7d4-00e0-4369-8e3e-33176213fe85)

**Comment by kakachiex2** [comment]
Is the way it works need to invert the mask.

**Comment by flowtyone** [comment]
Yes, this is intentional, the model was trained on grey background images. look here for a proper workflow: https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/blob/master/workflow_rembg.json
