### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by amirkerr** [flowtyone/ComfyUI-Flowty-TripoSR#27]
Hello!

I have 3070Ti with 8Gb memory.
Windows 10 x64
32Gb RAM

Please help me find out what's wrong
![123](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/66627221/36788c28-741a-4d93-9c48-a13ace796ffb)
![1212](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/66627221/047b8de2-0121-4cca-83f3-13f58d3620a7)

**Comment by flowtyone** [comment]
Looks like you don't have enough available memory, try to reduce the chunk_size parameter to 4096

**Comment by amirkerr** [comment]
Seems like it works :) Thank you!
