### ISSUE TITLE
How to save generated 3D model via nodes? Thanks

### ISSUE THREAD

**Issue by assassindesign** [flowtyone/ComfyUI-Flowty-TripoSR#29]
The current node only has a preview. Can the generated preview model be saved as a 3D model? Thanks

**Comment by amirkerr** [comment]
> The current node only has a preview. Can the generated preview model be saved as a 3D model? Thanks

Heya! You should find them in your 'output' folder ;)

**Comment by assassindesign** [comment]
haha cool! thanks!

**Comment by 3blackbar** [comment]
But they have no texture saved,  and its no use for them really cause if they would, id try to img2img texture to do better details
