### ISSUE TITLE
TripoSR Viewer File not found 404

### ISSUE THREAD

**Issue by IVIaV** [flowtyone/ComfyUI-Flowty-TripoSR#46]
### **Problem**
I installed TripoSR on 09.05.2024 and all nodes worked except for the viewer.

**Symptoms**
The only error that is displayed is the one in the node: "Error 404: File Not Found That request doesn't seem to lead anywhere, unfortunately."

![pic0](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/169431888/e2a15856-2214-4617-8783-ecfb5d9814f3)

No error message in the server log or in the CMD. The process runs to the end and does not stop at the missing node. A file is not created.

**Error message in the webbrowser:** "Error loading extension /extensions/ComfyUI-Flowty-TripoSR/js/threeVisualizer.js TypeError: The specifier "three" was a blank specifier, but was not reassigned to anything. Relative module specifiers must begin with "./", "../" or "/"."

I followed the instructions from here "_https://github.com/flowtyone/ComfyUI-Flowty-TripoSR_".

I only have entered new versions of the latest extensions in the requirements.txt:

omegaconf==2.3.0
pillow==10.2.0
einops==0.7.0
transformers==4.38.2
trimesh==4.3.0
huggingface-hub
imageio[ffmpeg]
scikit-image

**Assumption**

1. I have not installed Comfyui 3d at the same time installing TripoSR because of errors. Do I need this as an extra node?
2. I can run threeVisualizer.html, the websites "_https://unpkg.com/three@latest/build/three.module.js_" and "_https://unpkg.com/three@latest/examples/jsm_" are accessible, but I suspect that this is where the error lies and a file is missing.
3. Of course, I also had other 3D nodes installed (but uninstalled them again at the time of TripoSR): ComfyUI-3D-Pack, Tripo for ComfyUI, ComfyUI-Flowty-CRM
The viewer did not work with any of the nodes... **So it must actually have something to do with the threeVisualizer**
![pic1](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/169431888/31938fd8-e5b4-4139-8dec-69bd6d2fc81d)

Interestingly, the threeVisualizer.js is loaded, but the html file gives the same error: 404 file not found

### Specifications:
Windows 10 22H2
StableSwarm Version V0.6.2.0
ComfyUi Version 2169 (2024-05-09)
Manager: V2.20.2
Web Browser: Firefox 125.0.3

**Comment by IVIaV** [comment]
Hey :)

for everyone who has the same problem, here is the solution ...

The problem occures because of the changed directories of ComfyUi. The web/html/threeVisualizer.html and web/visualization.js data must been changed.

Thanks to mcmonkey4eva I found the problem now. For more information see here:

https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/pull/35/commits/4d4cc694c4c0f4e23dd2d4a6ae90037359e8f956

**Comment by gerroon** [comment]
Thanks, will you make a new releases so ComfyUI users can pull the updates thanks
