### ISSUE TITLE
When loading the graph, the following node types were not found:       TripoSRSampler     TripoSRViewer  Nodes that have failed to load will show as red on the graph.

### ISSUE THREAD

**Issue by kevinabantostudio** [flowtyone/ComfyUI-Flowty-TripoSR#8]
When I click Install Missing Custom Nodes, those nodes do not appear to install

When loading the graph, the following node types were not found: 

    TripoSRSampler
    TripoSRViewer

Nodes that have failed to load will show as red on the graph.

**Comment by kuri-pl** [comment]
Same here, I also tried to install it following the instructions on this repo page and ComfyUI still can't find the nodes

**Comment by ekswathi** [comment]
same problem

**Comment by flowtyone** [comment]
Hi @ekswathi @kevinabantostudio @kuri-pl please pull the latest changes, follow the setup instructions and restart comfyui.

**Comment by XTRMsavage** [comment]
Followed the instructions, done a git pull, but still not working?

<img width="866" alt="image" src="https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/90519573/fe24c88e-859d-4923-9463-fd38a6090643">

**Comment by RYG81** [comment]
in comfy manager verify if your nodes imported or not, by going to filter view for import failed.

**Comment by XTRMsavage** [comment]
> in comfy manager verify if your nodes imported or not, by going to filter view for import failed.

Thanks, worked!

**Comment by amirkerr** [comment]
> in comfy manager verify if your nodes imported or not, by going to filter view for import failed.

Heya! Could you please elaborate on filter view? Cause I see nothing there :\
![25](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/66627221/b5437924-73fd-4a0a-aa28-596a6a13b464)

**Comment by amirkerr** [comment]
> on top left there is filter option, choose import failed from that dropdown. That will list all nodes that failed to load. If this node is listed there, that means it's not installed properly. Like this ![msedge_VDnvT9tHC8](https://private-user-images.githubusercontent.com/10570236/310961826-6fa4bf1a-ba40-471b-823f-af1d99412e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Mjk0MDcsIm5iZiI6MTcwOTgyOTEwNywicGF0aCI6Ii8xMDU3MDIzNi8zMTA5NjE4MjYtNmZhNGJmMWEtYmE0MC00NzFiLTgyM2YtYWYxZDk5NDEyZTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NmE5NjRmZThmYzQ3OWM0OTM5NDY5YTE1NGM3ZDgyYWNiYjI4MGU3ODliMjE2ZGRmOTIyNmE3OTBiY2M3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lya8N-xQsH3MmmEu96WNkqp3yLOiAi6Nvh_q7dlUitU)

Thank you! But for some reason I don't have 'Failed' listed in the Filter :\ 
![233](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/66627221/841fb17e-b879-4da9-ba79-a8929be2ee51)

**Comment by amirkerr** [comment]
Ugh, I'm sorry guys!

Had to update (re-install) the Manager and it worked out :)

Thank youuuu!
